before:
  hooks:
    - go mod download

archives:
  - format: binary

builds:
  - 
    env:
    - CGO_ENABLED=0
    goarch:
    - arm
    - amd64
    - arm64
    ignore:
    - goos: darwin
      goarch: arm
    - goos: darwin
      goarch: arm64
